# 하이퍼파라미터 튜닝 범위 설정
# 각 파라미터별로 시도할 값들의 리스트

# 학습 관련 파라미터
training.batch_size: [16, 32, 64]           # 배치 크기
training.learning_rate: [0.001, 0.01, 0.02, 0.05]  # 학습률
training.weight_decay: [0.0001, 0.0005, 0.001]     # 가중치 감쇠
training.momentum: [0.9, 0.937, 0.95]              # 모멘텀

# 모델 구조 파라미터
model.head.reduction_ratio: [8, 16, 32]            # Attention reduction ratio
model.head.kernel_size: [3, 7, 11]                 # Spatial attention kernel
model.input_size: [416, 640, 832]                  # 입력 이미지 크기

# 손실 함수 가중치
training.loss.box: [0.05, 0.1, 0.2]               # Box loss 가중치
training.loss.cls: [0.3, 0.5, 0.7]                # Class loss 가중치
training.loss.obj: [0.7, 1.0, 1.3]                # Object loss 가중치

# 데이터 증강 파라미터
training.augmentation.fliplr: [0.0, 0.5, 0.8]     # 좌우 뒤집기 확률
training.augmentation.mixup: [0.0, 0.1, 0.2]      # Mixup 확률
training.augmentation.hsv_s: [0.5, 0.7, 0.9]      # 채도 변화